vim.o.background = "dark"
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.autoindent = true
vim.opt.cindent = true
vim.opt.smartindent = true
vim.opt.cursorline = true
vim.opt.autowrite = true
vim.opt.autoread = true
vim.opt.clipboard = "unnamedplus"
vim.opt.wrap = true
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.mouse = "a"
vim.opt.mousefocus = true
vim.g.formatoptions = "qrn1"
vim.opt.guifont = "Iosevka Nerd Font Mono"
vim.opt.showmode = false
vim.opt.timeoutlen = 500
vim.opt.updatetime = 100
vim.wo.signcolumn = "yes"
vim.opt.scrolloff = 5
vim.opt.wrap = false
vim.opt.ttimeoutlen = 5
vim.opt.virtualedit = "block"
vim.opt.undofile = true
vim.opt.undodir = vim.fn.stdpath("data") .. "undo"
vim.opt.shell = "/bin/bash"
-- vim.opt.expandtab = true
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.showcmd = true
vim.opt.backspace = "2"
vim.opt.laststatus = 2
-- vim.opt.foldmethod = "expr"
-- vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
